name: Enviar Noticias Diarias

on:
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Execute script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python main.py

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Noticias del día - Argentina"
          to: "ffranpatrito73@gmail.com"
          from: "Noticiero Automático"
          body: file://informe_noticias.txt